package com.example.mobile_moviescatalog2023.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFC315E)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF91002C)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDADB)
val md_theme_dark_secondary = Color(0xFFE6BDBF)
val md_theme_dark_onSecondary = Color(0xFF44292B)
val md_theme_dark_secondaryContainer = Color(0xFF5C3F41)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDADB)
val md_theme_dark_tertiary = Color(0xFFE8C08E)
val md_theme_dark_onTertiary = Color(0xFF432C06)
val md_theme_dark_tertiaryContainer = Color(0xFF5D421B)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB5)
val md_theme_dark_error = Color(0xFFE64646)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1D1D)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_outline = Color(0xFF5E5E5E)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inverseSurface = Color(0xFFECE0DF)
val md_theme_dark_inversePrimary = Color(0xFFBE003D)
val md_theme_dark_surfaceTint = Color(0xFFFFB2B8)
val md_theme_dark_outlineVariant = Color(0xFF524344)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF292929)
val md_theme_dark_onSurface = Color(0xFF909499)
val md_theme_dark_surfaceVariant = Color(0xFF404040)
val md_theme_dark_onSurfaceVariant = Color(0xFF909499)